NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: C:\Program Files\Python312\python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

## create array using numpy
## create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [11]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1,5) ## 1 row and 5 columns



array([[1, 2, 3, 4, 5]])

In [13]:

arr2 = np.array([[1, 2, 3, 4, 5]])
print(arr2.shape)

(1, 5)


In [12]:
## create a 2D array
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2.shape)

(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
print(np.ones((3,4)))
print()
print(np.zeros((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [20]:
## identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
## Attributes of numpy array
arr= np.array([[1,2,3],[4,5,6]])
print(f"Array: \n{arr}\n")
print(f"Shape: \n{arr.shape} \n")
print(f"Size: \n{arr.size}\n")
print(f"Data type: \n{arr.dtype}\n")
print(f"Dimension: \n{arr.ndim}\n")
print(f"Item size (in bytes): \n{arr.itemsize}\n")

Array: 
[[1 2 3]
 [4 5 6]]

Shape: 
(2, 3) 

Size: 
6

Data type: 
int64

Dimension: 
2

Item size (in bytes): 
8



In [36]:
## Numpy vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
## element wise operations
## addition, subtraction, multiplication, division, power
print(f"Addition {arr1 + arr2}")
print(f"Subtraction {arr1 - arr2}")
print(f"Multiplication {arr1 * arr2}")
print(f"Division {arr1 / arr2}")
print(f"Power {arr1 ** arr2}")



Addition [ 7  9 11 13 15]
Subtraction [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
Division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Power [      1     128    6561  262144 9765625]


In [44]:
## Universal functions
arr = np.array([2,3,4,5,6])

## square root
print(f"square root: \n {np.sqrt(arr)}\n")

## exponential
print(f"exponential: \n {np.exp(arr)}\n")

## log
print(f"log: \n {np.log(arr)}\n")

## sin
print(f"sin: \n {np.sin(arr)}\n")


square root: 
 [1.41421356 1.73205081 2.         2.23606798 2.44948974]

exponential: 
 [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]

log: 
 [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]

sin: 
 [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]



In [71]:
## Indexing and slicing
arr = np.array([
    [1,2,3,4,5,6,7,8,9],
    [10,11,12,13,14,15,16,17,18],
    [19,20,21,22,23,24,25,26,27]
    ])


print(f"Array : \n{arr}\n")
print(f"Dimension:  \n{arr.ndim}\n")

## indexing in 2D array
print(arr[0][0])
## alternative methos of indexing
print(arr[0,0])

print(arr[1:,0:])

print(arr[1:,-2:])
print(arr[1:,7:])

print(f"\n{arr[0:2,-2:]}\n")



Array : 
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

Dimension:  
2

1
1
[[10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]
[[17 18]
 [26 27]]
[[17 18]
 [26 27]]

[[ 8  9]
 [17 18]]



In [79]:
arr[1:] = 100
print(arr)

## changing the elements of the array
print("\n here, i am changing array[2:,-1:] to 200 :") 
arr[2:,-1:] = 200
print(arr)

[[  1   2   3   4   5   6   7   8   9]
 [100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 100]]

 here, i am changing array[2:,-1:] to 200 :
[[  1   2   3   4   5   6   7   8   9]
 [100 100 100 100 100 100 100 100 100]
 [100 100 100 100 100 100 100 100 200]]


In [82]:
## statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

## calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data
normalized_data = (data - mean) / std_dev
print(f"Normalized data: {normalized_data}")


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [91]:
## statistical concepts -- Standardization

data = np.array([1,2,2,2,3,4,5])

## mean 
mean = np.mean(data)
print(f"Mean: {mean}")

## median
median = np.median(data)
print(f"Median: {median}")

## mode
from scipy import stats
mode_result = stats.mode(data, keepdims=True)
print(f"Mode: {mode_result.mode[0]}, Count: {mode_result.count[0]}")


## standard deviation
std_dev = np.std(data)
print(f"Standard deviation: {std_dev}")

## variance
variance = np.var(data)
print(f"Variance: {variance}")

## percentile
percentile = np.percentile(data, 50)
print(f"Percentile: {percentile}")

## correlation
data1 = np.array([1,2,3,4,5])
data2 = np.array([6,7,8,9,10])
correlation = np.corrcoef(data1, data2)
print(f"Correlation: \n{correlation}")

## covariance
covariance = np.cov(data1, data2)
print(f"Covariance: \n{covariance}")

## random numbers
## generate random numbers
random_numbers = np.random.rand(5)
print(f"Random numbers: {random_numbers}")

## generate random numbers between 0 and 100
random_numbers = np.random.randint(0, 100, 5)
print(f"Random numbers: {random_numbers}")

## generate random numbers between 0 and 1
random_numbers = np.random.rand(5)
print(f"Random numbers: {random_numbers}")



Mean: 2.7142857142857144
Median: 2.0
Mode: 2, Count: 3
Standard deviation: 1.2777531299998799
Variance: 1.63265306122449
Percentile: 2.0
Correlation: 
[[1. 1.]
 [1. 1.]]
Covariance: 
[[2.5 2.5]
 [2.5 2.5]]
Random numbers: [0.92258299 0.77971765 0.23862158 0.24518317 0.76963527]
Random numbers: [31 48  2  1 56]
Random numbers: [6.41801519e-01 6.38871727e-02 7.97181991e-01 2.86135652e-06
 6.99549508e-01]


In [100]:
## Logical operations
data = np.array([1,2,3,4,5])
print(f"Is 1 in data: {1 in data}")

print(data>3)
print(data[data>3])
print(data[data%2==0])


print(data[(data>2) & (data<5)])



Is 1 in data: True
[False False False  True  True]
[4 5]
[2 4]
[3 4]
